### ISSUE TITLE
Slueth for css

### ISSUE THREAD

**Issue by MortalCatalyst** [tpope/vim-sleuth#22]
I loaded slueth as I was trying to get one last thing in vim that I was having trouble with and that is indenting for css

so I loaded a styles.css file which is indented such as this.

`````` css
div {
    margin:0;
    padding:0;
  }
div div {
   background: #A4CA39;
   position: relative;
}
.android {
    height: 404px; width: 334px;
    margin: 100px auto;
  }
``````

But when I edited to contiue I still didn't get correct indentation i got this, is there a way to get it right?

```css
 .body {
  }
``````
