### ISSUE TITLE
YAML files performance issues under 

### ISSUE THREAD

**Issue by shmileee** [tpope/vim-sleuth#67]
Looks like opening even small YAML files under WSL1 (Ubuntu 20.04) with `vim-sleuth` enabled takes more time than it should. 

Without:
```
time vim site.yaml

________________________________________________________
Executed in    1.84 secs   fish           external
   usr time   93.75 millis    0.00 micros   93.75 millis
   sys time  156.25 millis    0.00 micros  156.25 millis
```

With:
```
time vim site.yaml

________________________________________________________
Executed in    3.56 secs   fish           external
   usr time    0.44 secs    0.00 micros    0.44 secs
   sys time    1.83 secs    0.00 micros    1.83 secs
```

`vim site.yml --startuptime vim.log`: https://gist.github.com/shmileee/3183bd6225ddc11a6c0b55abbfa62d9c

`.vimrc` for reference: https://github.com/shmileee/dotfiles/blob/3037be9b6828d2a590d2a3cb1bc1582977626419/.vimrc
Vim version: `VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)`

YAML file for referecnce:
```
---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
  environment: "{{ proxy_env }}"

- hosts: master
  gather_facts: no
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  gather_facts: no
  become: yes
  roles:
    - role: k3s/node

- hosts: master
  gather_facts: no
  become: yes
  roles:
    - role: addons/common
      tags: common
    - role: addons/metallb
    - role: addons/traefik
  environment: "{{ proxy_env }}"
  tags: addons
```
